manifest:
  self:
    path: app

  defaults:
    remote: nrfconnect

  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      remote: nrfconnect
      repo-path: sdk-nrf
      revision: main
      import: true
